//! Minidump Decoder Tool
//! 
//! This tool reads binary minidump files generated by the Polymera OS kernel
//! and produces human-readable crash reports for debugging.

use std::fs;
use std::path::Path;
use std::io::{self, Write};
use std::collections::HashMap;

/// Minidump header structure (must match kernel definition)
#[repr(C, packed)]
#[derive(Debug, Clone, Copy)]
pub struct MinidumpHeader {
    pub magic: [u8; 4],
    pub version: u32,
    pub timestamp: u64,
    pub total_size: u32,
    pub flags: u32,
    pub checksum: u32,
    pub reserved: [u8; 16],
}

/// CPU register state (must match kernel definition)
#[repr(C, packed)]
#[derive(Debug, Clone, Copy)]
pub struct CpuRegisters {
    pub rax: u64, pub rbx: u64, pub rcx: u64, pub rdx: u64,
    pub rsi: u64, pub rdi: u64, pub rbp: u64, pub rsp: u64,
    pub r8: u64, pub r9: u64, pub r10: u64, pub r11: u64,
    pub r12: u64, pub r13: u64, pub r14: u64, pub r15: u64,
    pub rip: u64, pub rflags: u64,
    pub cs: u64, pub ds: u64, pub es: u64, pub fs: u64, pub gs: u64, pub ss: u64,
    pub cr0: u64, pub cr2: u64, pub cr3: u64, pub cr4: u64, pub cr8: u64,
    pub dr0: u64, pub dr1: u64, pub dr2: u64, pub dr3: u64, pub dr6: u64, pub dr7: u64,
    pub msr_efer: u64, pub msr_star: u64, pub msr_lstar: u64, pub msr_cstar: u64,
    pub msr_sfmask: u64, pub msr_fs_base: u64, pub msr_gs_base: u64, pub msr_kernel_gs_base: u64,
}

/// Audit entry structure (must match kernel definition)
#[repr(C, packed)]
#[derive(Debug, Clone, Copy)]
pub struct AuditEntry {
    pub timestamp: u64,
    pub event_type: u32,
    pub process_id: u64,
    pub user_id: u64,
    pub data: [u8; 32],
}

/// Serial buffer entry structure (must match kernel definition)
#[repr(C, packed)]
#[derive(Debug, Clone, Copy)]
pub struct SerialBufferEntry {
    pub timestamp: u64,
    pub length: u16,
    pub data: [u8; 64],
}

/// Kernel build information structure (must match kernel definition)
#[repr(C, packed)]
#[derive(Debug, Clone, Copy)]
pub struct KernelBuildInfo {
    pub build_timestamp: u64,
    pub git_hash: [u8; 8],
    pub version_string: [u8; 32],
    pub build_flags: u64,
    pub target_arch: [u8; 16],
    pub target_platform: [u8; 16],
}

/// Memory region structure (must match kernel definition)
#[repr(C, packed)]
#[derive(Debug, Clone, Copy)]
pub struct MemoryRegion {
    pub start_address: u64,
    pub end_address: u64,
    pub protection: u32,
    pub memory_type: u32,
    pub reserved: [u8; 8],
}

/// Complete minidump structure (must match kernel definition)
#[repr(C, packed)]
pub struct Minidump {
    pub header: MinidumpHeader,
    pub cpu_registers: CpuRegisters,
    pub audit_entries: [AuditEntry; 64],
    pub audit_entry_count: u32,
    pub serial_buffer: [SerialBufferEntry; 32],
    pub serial_entry_count: u32,
    pub build_info: KernelBuildInfo,
    pub stack_trace: [u64; 16],
    pub stack_trace_count: u32,
    pub memory_regions: [MemoryRegion; 8],
    pub memory_region_count: u32,
}

/// Minidump flags
pub const MINIDUMP_FLAG_CPU_REGS: u32 = 1 << 0;
pub const MINIDUMP_FLAG_AUDIT_ENTRIES: u32 = 1 << 1;
pub const MINIDUMP_FLAG_SERIAL_BUFFER: u32 = 1 << 2;
pub const MINIDUMP_FLAG_BUILD_INFO: u32 = 1 << 3;
pub const MINIDUMP_FLAG_STACK_TRACE: u32 = 1 << 4;
pub const MINIDUMP_FLAG_MEMORY_REGIONS: u32 = 1 << 5;

/// Minidump decoder
pub struct MinidumpDecoder {
    data: Vec<u8>,
    minidump: Option<Minidump>,
}

impl MinidumpDecoder {
    /// Create a new decoder from file data
    pub fn new(data: Vec<u8>) -> Self {
        Self {
            data,
            minidump: None,
        }
    }
    
    /// Parse the minidump data
    pub fn parse(&mut self) -> Result<(), String> {
        if self.data.len() < std::mem::size_of::<MinidumpHeader>() {
            return Err("Data too short for minidump header".to_string());
        }
        
        // Parse header
        let header = unsafe {
            &*(self.data.as_ptr() as *const MinidumpHeader)
        };
        
        // Validate magic number
        if header.magic != [b'P', b'O', b'L', b'Y'] {
            return Err("Invalid magic number - not a Polymera minidump".to_string());
        }
        
        // Validate version
        if header.version != 1 {
            return Err(format!("Unsupported minidump version: {}", header.version));
        }
        
        // Validate size
        if header.total_size as usize > self.data.len() {
            return Err(format!("Minidump size mismatch: expected {}, got {}", 
                             header.total_size, self.data.len()));
        }
        
        // Parse full minidump
        if self.data.len() < std::mem::size_of::<Minidump>() {
            return Err("Data too short for complete minidump".to_string());
        }
        
        let minidump = unsafe {
            &*(self.data.as_ptr() as *const Minidump)
        };
        
        self.minidump = Some(*minidump);
        
        Ok(())
    }
    
    /// Generate a human-readable crash report
    pub fn generate_report(&self) -> Result<String, String> {
        let minidump = self.minidump.as_ref()
            .ok_or("No minidump parsed")?;
        
        let mut report = String::new();
        
        // Header information
        report.push_str(&format!("=== POLYMERA OS CRASH REPORT ===\n"));
        report.push_str(&format!("Generated: {}\n", 
                               format_timestamp(minidump.header.timestamp)));
        report.push_str(&format!("Version: {}\n", minidump.header.version));
        report.push_str(&format!("Size: {} bytes\n", minidump.header.total_size));
        report.push_str(&format!("Flags: 0x{:08x}\n", minidump.header.flags));
        report.push_str(&format!("Checksum: 0x{:08x}\n", minidump.header.checksum));
        report.push_str(&format!("\n"));
        
        // CPU registers
        if minidump.header.flags & MINIDUMP_FLAG_CPU_REGS != 0 {
            report.push_str(&format!("=== CPU REGISTERS ===\n"));
            report.push_str(&format!("RAX: 0x{:016x}  RBX: 0x{:016x}\n", 
                                   minidump.cpu_registers.rax, minidump.cpu_registers.rbx));
            report.push_str(&format!("RCX: 0x{:016x}  RDX: 0x{:016x}\n", 
                                   minidump.cpu_registers.rcx, minidump.cpu_registers.rdx));
            report.push_str(&format!("RSI: 0x{:016x}  RDI: 0x{:016x}\n", 
                                   minidump.cpu_registers.rsi, minidump.cpu_registers.rdi));
            report.push_str(&format!("RBP: 0x{:016x}  RSP: 0x{:016x}\n", 
                                   minidump.cpu_registers.rbp, minidump.cpu_registers.rsp));
            report.push_str(&format!("R8:  0x{:016x}  R9:  0x{:016x}\n", 
                                   minidump.cpu_registers.r8, minidump.cpu_registers.r9));
            report.push_str(&format!("R10: 0x{:016x}  R11: 0x{:016x}\n", 
                                   minidump.cpu_registers.r10, minidump.cpu_registers.r11));
            report.push_str(&format!("R12: 0x{:016x}  R13: 0x{:016x}\n", 
                                   minidump.cpu_registers.r12, minidump.cpu_registers.r13));
            report.push_str(&format!("R14: 0x{:016x}  R15: 0x{:016x}\n", 
                                   minidump.cpu_registers.r14, minidump.cpu_registers.r15));
            report.push_str(&format!("RIP: 0x{:016x}  RFLAGS: 0x{:016x}\n", 
                                   minidump.cpu_registers.rip, minidump.cpu_registers.rflags));
            report.push_str(&format!("\n"));
            
            // Control registers
            report.push_str(&format!("=== CONTROL REGISTERS ===\n"));
            report.push_str(&format!("CS: 0x{:04x}  DS: 0x{:04x}  ES: 0x{:04x}\n", 
                                   minidump.cpu_registers.cs as u16, 
                                   minidump.cpu_registers.ds as u16, 
                                   minidump.cpu_registers.es as u16));
            report.push_str(&format!("FS: 0x{:04x}  GS: 0x{:04x}  SS: 0x{:04x}\n", 
                                   minidump.cpu_registers.fs as u16, 
                                   minidump.cpu_registers.gs as u16, 
                                   minidump.cpu_registers.ss as u16));
            report.push_str(&format!("CR0: 0x{:016x}  CR2: 0x{:016x}\n", 
                                   minidump.cpu_registers.cr0, minidump.cpu_registers.cr2));
            report.push_str(&format!("CR3: 0x{:016x}  CR4: 0x{:016x}  CR8: 0x{:016x}\n", 
                                   minidump.cpu_registers.cr3, minidump.cpu_registers.cr4, 
                                   minidump.cpu_registers.cr8));
            report.push_str(&format!("\n"));
            
            // Debug registers
            report.push_str(&format!("=== DEBUG REGISTERS ===\n"));
            report.push_str(&format!("DR0: 0x{:016x}  DR1: 0x{:016x}\n", 
                                   minidump.cpu_registers.dr0, minidump.cpu_registers.dr1));
            report.push_str(&format!("DR2: 0x{:016x}  DR3: 0x{:016x}\n", 
                                   minidump.cpu_registers.dr2, minidump.cpu_registers.dr3));
            report.push_str(&format!("DR6: 0x{:016x}  DR7: 0x{:016x}\n", 
                                   minidump.cpu_registers.dr6, minidump.cpu_registers.dr7));
            report.push_str(&format!("\n"));
        }
        
        // Stack trace
        if minidump.header.flags & MINIDUMP_FLAG_STACK_TRACE != 0 && minidump.stack_trace_count > 0 {
            report.push_str(&format!("=== STACK TRACE ===\n"));
            for i in 0..minidump.stack_trace_count as usize {
                if minidump.stack_trace[i] != 0 {
                    report.push_str(&format!("Frame {}: 0x{:016x}\n", i, minidump.stack_trace[i]));
                }
            }
            report.push_str(&format!("\n"));
        }
        
        // Build information
        if minidump.header.flags & MINIDUMP_FLAG_BUILD_INFO != 0 {
            report.push_str(&format!("=== KERNEL BUILD INFO ===\n"));
            report.push_str(&format!("Build Time: {}\n", 
                                   format_timestamp(minidump.build_info.build_timestamp)));
            report.push_str(&format!("Version: {}\n", 
                                   format_null_terminated_string(&minidump.build_info.version_string)));
            report.push_str(&format!("Architecture: {}\n", 
                                   format_null_terminated_string(&minidump.build_info.target_arch)));
            report.push_str(&format!("Platform: {}\n", 
                                   format_null_terminated_string(&minidump.build_info.target_platform)));
            report.push_str(&format!("Build Flags: 0x{:016x}\n", minidump.build_info.build_flags));
            report.push_str(&format!("Git Hash: {}\n", 
                                   format_git_hash(&minidump.build_info.git_hash)));
            report.push_str(&format!("\n"));
        }
        
        // Audit entries
        if minidump.header.flags & MINIDUMP_FLAG_AUDIT_ENTRIES != 0 && minidump.audit_entry_count > 0 {
            report.push_str(&format!("=== AUDIT TRAIL (Last {} entries) ===\n", 
                                   minidump.audit_entry_count));
            for i in 0..minidump.audit_entry_count as usize {
                let entry = &minidump.audit_entries[i];
                if entry.timestamp != 0 {
                    report.push_str(&format!("[{}] Event {}: PID {}, UID {}, Data: {}\n",
                                           format_timestamp(entry.timestamp),
                                           entry.event_type,
                                           entry.process_id,
                                           entry.user_id,
                                           format_hex_data(&entry.data)));
                }
            }
            report.push_str(&format!("\n"));
        }
        
        // Serial buffer
        if minidump.header.flags & MINIDUMP_FLAG_SERIAL_BUFFER != 0 && minidump.serial_entry_count > 0 {
            report.push_str(&format!("=== SERIAL OUTPUT (Last {} entries) ===\n", 
                                   minidump.serial_entry_count));
            for i in 0..minidump.serial_entry_count as usize {
                let entry = &minidump.serial_buffer[i];
                if entry.timestamp != 0 && entry.length > 0 {
                    report.push_str(&format!("[{}] {} bytes: {}\n",
                                           format_timestamp(entry.timestamp),
                                           entry.length,
                                           format_serial_data(&entry.data[..entry.length as usize])));
                }
            }
            report.push_str(&format!("\n"));
        }
        
        // Memory regions
        if minidump.header.flags & MINIDUMP_FLAG_MEMORY_REGIONS != 0 && minidump.memory_region_count > 0 {
            report.push_str(&format!("=== MEMORY REGIONS ===\n"));
            for i in 0..minidump.memory_region_count as usize {
                let region = &minidump.memory_regions[i];
                if region.start_address != 0 || region.end_address != 0 {
                    report.push_str(&format!("Region {}: 0x{:016x} - 0x{:016x} (Prot: 0x{:08x}, Type: 0x{:08x})\n",
                                           i,
                                           region.start_address,
                                           region.end_address,
                                           region.protection,
                                           region.memory_type));
                }
            }
            report.push_str(&format!("\n"));
        }
        
        report.push_str(&format!("=== END OF CRASH REPORT ===\n"));
        
        Ok(report)
    }
    
    /// Validate the minidump checksum
    pub fn validate_checksum(&self) -> Result<bool, String> {
        let minidump = self.minidump.as_ref()
            .ok_or("No minidump parsed")?;
        
        let calculated = self.calculate_checksum();
        let stored = minidump.header.checksum;
        
        Ok(calculated == stored)
    }
    
    /// Calculate checksum of the minidump data
    fn calculate_checksum(&self) -> u32 {
        let mut checksum: u32 = 0;
        for &byte in &self.data {
            checksum = checksum.wrapping_add(byte as u32);
        }
        checksum
    }
}

/// Format timestamp as human-readable string
fn format_timestamp(timestamp: u64) -> String {
    // Convert milliseconds to seconds for display
    let seconds = timestamp / 1000;
    format!("{}s", seconds)
}

/// Format null-terminated string
fn format_null_terminated_string(bytes: &[u8]) -> String {
    let mut result = String::new();
    for &byte in bytes {
        if byte == 0 {
            break;
        }
        if byte.is_ascii() && !byte.is_ascii_control() {
            result.push(byte as char);
        } else {
            result.push_str(&format!("\\x{:02x}", byte));
        }
    }
    result
}

/// Format git hash
fn format_git_hash(bytes: &[u8]) -> String {
    let mut result = String::new();
    for &byte in bytes {
        result.push_str(&format!("{:02x}", byte));
    }
    result
}

/// Format hex data
fn format_hex_data(bytes: &[u8]) -> String {
    let mut result = String::new();
    for &byte in bytes {
        if byte != 0 {
            result.push_str(&format!("{:02x} ", byte));
        }
    }
    result.trim().to_string()
}

/// Format serial data
fn format_serial_data(bytes: &[u8]) -> String {
    let mut result = String::new();
    for &byte in bytes {
        if byte.is_ascii() && !byte.is_ascii_control() {
            result.push(byte as char);
        } else {
            result.push_str(&format!("\\x{:02x}", byte));
        }
    }
    result
}

/// Main function for command-line usage
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().collect();
    
    if args.len() != 2 {
        eprintln!("Usage: {} <minidump_file>", args[0]);
        eprintln!("");
        eprintln!("Decodes a Polymera OS kernel minidump file and generates a crash report.");
        eprintln!("");
        eprintln!("Example:");
        eprintln!("  {} kernel_crash.bin", args[0]);
        std::process::exit(1);
    }
    
    let file_path = &args[1];
    
    // Read the minidump file
    println!("Reading minidump file: {}", file_path);
    let data = fs::read(file_path)?;
    println!("Read {} bytes", data.len());
    
    // Create decoder and parse
    let mut decoder = MinidumpDecoder::new(data);
    match decoder.parse() {
        Ok(()) => println!("Successfully parsed minidump"),
        Err(e) => {
            eprintln!("Failed to parse minidump: {}", e);
            std::process::exit(1);
        }
    }
    
    // Validate checksum
    match decoder.validate_checksum() {
        Ok(valid) => {
            if valid {
                println!("Checksum validation: PASSED");
            } else {
                println!("Checksum validation: FAILED (data may be corrupted)");
            }
        }
        Err(e) => println!("Checksum validation: ERROR ({})", e),
    }
    
    // Generate and display report
    match decoder.generate_report() {
        Ok(report) => {
            println!("\n{}", report);
        }
        Err(e) => {
            eprintln!("Failed to generate report: {}", e);
            std::process::exit(1);
        }
    }
    
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_format_timestamp() {
        assert_eq!(format_timestamp(1000), "1s");
        assert_eq!(format_timestamp(1500), "1s");
        assert_eq!(format_timestamp(0), "0s");
    }
    
    #[test]
    fn test_format_null_terminated_string() {
        let data = b"Hello\0World\0";
        assert_eq!(format_null_terminated_string(data), "Hello");
        
        let data = b"Test\x00\x01\x02";
        assert_eq!(format_null_terminated_string(data), "Test\\x00\\x01\\x02");
    }
    
    #[test]
    fn test_format_git_hash() {
        let hash = [0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0];
        assert_eq!(format_git_hash(&hash), "123456789abcdef0");
    }
    
    #[test]
    fn test_format_hex_data() {
        let data = [0x01, 0x02, 0x00, 0x03, 0x00, 0x04];
        assert_eq!(format_hex_data(&data), "01 02 03 04");
    }
}
