load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "ngfs-ipfs-export",
    srcs = ["main.go"],
    importpath = "github.com/polymera-os/polymera-os/go/tools/ngfs-ipfs-export",
    visibility = ["//visibility:public"],
)
