timeout: 0
serial: yes
verbose: yes
graphics: no

/Polymera OS
    protocol: limine
    path: boot():/boot/kernel.elf
    module_path: boot():/boot/initramfs.cpio.gz
    module_string: initramfs
    cmdline: loglevel=7 avengers=assemble console=ttyS0,115200 console=tty0 earlycon
