// Generated by abi-gen
// Schema hash: {{ schema_hash }}
// Generated at: {{ now }}
// DO NOT EDIT - This file is automatically generated

use std::collections::HashMap;
use std::sync::Once;

// Import the generated ABI stubs
use polymera_os::syscalls;

/// Test configuration for ABI conformance tests
#[derive(Debug, Clone)]
pub struct ConformanceTestConfig {
    /// Whether to run destructive tests
    pub destructive: bool,
    /// Whether to run performance tests
    pub performance: bool,
    /// Maximum test iterations
    pub max_iterations: usize,
    /// Test timeout in seconds
    pub timeout_seconds: u64,
}

impl Default for ConformanceTestConfig {
    fn default() -> Self {
        Self {
            destructive: false,
            performance: false,
            max_iterations: 1000,
            timeout_seconds: 30,
        }
    }
}

/// Test result for a single syscall test
#[derive(Debug, Clone)]
pub struct SyscallTestResult {
    /// Name of the syscall tested
    pub syscall_name: String,
    /// Test case description
    pub test_case: String,
    /// Whether the test passed
    pub passed: bool,
    /// Expected result
    pub expected: String,
    /// Actual result
    pub actual: String,
    /// Error message if test failed
    pub error: Option<String>,
    /// Execution time in microseconds
    pub execution_time: Option<u64>,
}

/// Overall conformance test results
#[derive(Debug)]
pub struct ConformanceTestResults {
    /// Total tests run
    pub total_tests: usize,
    /// Tests passed
    pub passed: usize,
    /// Tests failed
    pub failed: usize,
    /// Test results by syscall
    pub results_by_syscall: HashMap<String, Vec<SyscallTestResult>>,
    /// Overall pass rate
    pub pass_rate: f64,
    /// Test duration in seconds
    pub duration: f64,
}

impl ConformanceTestResults {
    /// Create new test results
    fn new() -> Self {
        Self {
            total_tests: 0,
            passed: 0,
            failed: 0,
            results_by_syscall: HashMap::new(),
            pass_rate: 0.0,
            duration: 0.0,
        }
    }
    
    /// Add a test result
    fn add_result(&mut self, result: SyscallTestResult) {
        let syscall_name = result.syscall_name.clone();
        
        if !self.results_by_syscall.contains_key(&syscall_name) {
            self.results_by_syscall.insert(syscall_name.clone(), Vec::new());
        }
        
        if let Some(results) = self.results_by_syscall.get_mut(&syscall_name) {
            results.push(result.clone());
        }
        
        self.total_tests += 1;
        if result.passed {
            self.passed += 1;
        } else {
            self.failed += 1;
        }
    }
    
    /// Calculate pass rate
    fn calculate_pass_rate(&mut self) {
        if self.total_tests > 0 {
            self.pass_rate = (self.passed as f64) / (self.total_tests as f64) * 100.0;
        }
    }
    
    /// Print test summary
    fn print_summary(&self) {
        println!("\n=== ABI Conformance Test Summary ===");
        println!("Total Tests: {}", self.total_tests);
        println!("Passed: {}", self.passed);
        println!("Failed: {}", self.failed);
        println!("Pass Rate: {:.2}%", self.pass_rate);
        println!("Duration: {:.2}s", self.duration);
        
        if self.failed > 0 {
            println!("\nFailed Tests:");
            for (syscall, results) in &self.results_by_syscall {
                for result in results {
                    if !result.passed {
                        println!("  {} - {}: {}", syscall, result.test_case, result.error.as_ref().unwrap_or(&"Unknown error".to_string()));
                    }
                }
            }
        }
    }
}

/// ABI conformance test suite
pub struct AbiConformanceTestSuite {
    config: ConformanceTestConfig,
    results: ConformanceTestResults,
}

impl AbiConformanceTestSuite {
    /// Create a new test suite
    pub fn new(config: ConformanceTestConfig) -> Self {
        Self {
            config,
            results: ConformanceTestResults::new(),
        }
    }
    
    /// Run all conformance tests
    pub fn run_all_tests(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let start_time = std::time::Instant::now();
        
        println!("Starting ABI conformance tests...");
        println!("Config: {:?}", self.config);
        
        // Test each syscall
        self.test_sys_yield()?;
        self.test_sys_exit()?;
        self.test_sys_send()?;
        self.test_sys_recv()?;
        self.test_sys_cap_create()?;
        self.test_sys_cap_verify()?;
        self.test_sys_get_features()?;
        self.test_sys_get_time()?;
        self.test_sys_mmap()?;
        self.test_sys_munmap()?;
        
        // Calculate final results
        let duration = start_time.elapsed();
        self.results.duration = duration.as_secs_f64();
        self.results.calculate_pass_rate();
        
        // Print results
        self.results.print_summary();
        
        if self.results.failed > 0 {
            Err(format!("{} tests failed", self.results.failed).into())
        } else {
            Ok(())
        }
    }
    
    /// Test sys_yield
    fn test_sys_yield(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let syscall_name = "sys_yield".to_string();
        
        // Test 1: Basic yield
        let start = std::time::Instant::now();
        let result = syscalls::sys_yield();
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Basic yield".to_string(),
            passed: result.is_ok() && result.unwrap() == 0,
            expected: "Ok(0)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_ok() && result.unwrap() == 0 { None } else { Some("Yield failed".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        Ok(())
    }
    
    /// Test sys_exit
    fn test_sys_exit(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let syscall_name = "sys_exit".to_string();
        
        // Test 1: Exit with success code (this will terminate the test)
        if self.config.destructive {
            let test_result = SyscallTestResult {
                syscall_name: syscall_name.clone(),
                test_case: "Exit with success code".to_string(),
                passed: true, // We can't actually test this without terminating
                expected: "Process termination".to_string(),
                actual: "Not tested (destructive)".to_string(),
                error: None,
                execution_time: None,
            };
            
            self.results.add_result(test_result);
        }
        
        Ok(())
    }
    
    /// Test sys_send
    fn test_sys_send(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let syscall_name = "sys_send".to_string();
        
        // Test 1: Send with invalid destination
        let start = std::time::Instant::now();
        let result = syscalls::sys_send(0, b"test", 4, 0);
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Send to invalid destination".to_string(),
            passed: result.is_err(),
            expected: "Error (EPERM or EINVAL)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_err() { None } else { Some("Expected error for invalid destination".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        // Test 2: Send with null buffer
        let start = std::time::Instant::now();
        let result = syscalls::sys_send(1, std::ptr::null(), 0, 0);
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Send with null buffer".to_string(),
            passed: result.is_err(),
            expected: "Error (EFAULT)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_err() { None } else { Some("Expected error for null buffer".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        // Test 3: Send with oversized buffer
        let start = std::time::Instant::now();
        let result = syscalls::sys_send(1, b"test", 70000, 0); // > 65536
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Send with oversized buffer".to_string(),
            passed: result.is_err(),
            expected: "Error (EINVAL)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_err() { None } else { Some("Expected error for oversized buffer".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        Ok(())
    }
    
    /// Test sys_recv
    fn test_sys_recv(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let syscall_name = "sys_recv".to_string();
        
        // Test 1: Receive with null buffer
        let start = std::time::Instant::now();
        let result = syscalls::sys_recv(0, std::ptr::null_mut(), 0, 0);
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Receive with null buffer".to_string(),
            passed: result.is_err(),
            expected: "Error (EFAULT)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_err() { None } else { Some("Expected error for null buffer".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        // Test 2: Receive with oversized buffer
        let start = std::time::Instant::now();
        let result = syscalls::sys_recv(0, std::ptr::null_mut(), 70000, 0); // > 65536
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Receive with oversized buffer".to_string(),
            passed: result.is_err(),
            expected: "Error (EINVAL)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_err() { None } else { Some("Expected error for oversized buffer".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        Ok(())
    }
    
    /// Test sys_cap_create
    fn test_sys_cap_create(&mut self) -> Result<(), Box<dyn std::error::error::Error>> {
        let syscall_name = "sys_cap_create".to_string();
        
        // Test 1: Create capability with null issuer
        let start = std::time::Instant::now();
        let result = syscalls::sys_cap_create(std::ptr::null(), 0, 0, 0);
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Create capability with null issuer".to_string(),
            passed: result.is_err(),
            expected: "Error (EFAULT)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_err() { None } else { Some("Expected error for null issuer".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        // Test 2: Create capability with oversized issuer
        let start = std::time::Instant::now();
        let result = syscalls::sys_cap_create(b"test", 300, 0, 0); // > 256
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Create capability with oversized issuer".to_string(),
            passed: result.is_err(),
            expected: "Error (EINVAL)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_err() { None } else { Some("Expected error for oversized issuer".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        Ok(())
    }
    
    /// Test sys_cap_verify
    fn test_sys_cap_verify(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let syscall_name = "sys_cap_verify".to_string();
        
        // Test 1: Verify invalid capability ID
        let start = std::time::Instant::now();
        let result = syscalls::sys_cap_verify(99999, 0);
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Verify invalid capability ID".to_string(),
            passed: result.is_err(),
            expected: "Error (EINVAL)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_err() { None } else { Some("Expected error for invalid capability ID".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        Ok(())
    }
    
    /// Test sys_get_features
    fn test_sys_get_features(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let syscall_name = "sys_get_features".to_string();
        
        // Test 1: Get features
        let start = std::time::Instant::now();
        let result = syscalls::sys_get_features();
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Get features".to_string(),
            passed: result >= 0,
            expected: "Non-negative feature bitset".to_string(),
            actual: format!("{}", result),
            error: if result >= 0 { None } else { Some("Expected non-negative feature bitset".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        Ok(())
    }
    
    /// Test sys_get_time
    fn test_sys_get_time(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let syscall_name = "sys_get_time".to_string();
        
        // Test 1: Get time
        let start = std::time::Instant::now();
        let result = syscalls::sys_get_time();
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Get time".to_string(),
            passed: result > 0,
            expected: "Positive timestamp".to_string(),
            actual: format!("{}", result),
            error: if result > 0 { None } else { Some("Expected positive timestamp".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        // Test 2: Time monotonicity
        let time1 = syscalls::sys_get_time();
        std::thread::sleep(std::time::Duration::from_millis(1));
        let time2 = syscalls::sys_get_time();
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Time monotonicity".to_string(),
            passed: time2 > time1,
            expected: "Monotonic increasing time".to_string(),
            actual: format!("time1: {}, time2: {}", time1, time2),
            error: if time2 > time1 { None } else { Some("Expected monotonic increasing time".to_string()) },
            execution_time: None,
        };
        
        self.results.add_result(test_result);
        
        Ok(())
    }
    
    /// Test sys_mmap
    fn test_sys_mmap(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let syscall_name = "sys_mmap".to_string();
        
        // Test 1: Map with oversized length
        let start = std::time::Instant::now();
        let result = syscalls::sys_mmap(std::ptr::null_mut(), 2000000000, 0, 0, -1, 0); // > 1GB
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Map with oversized length".to_string(),
            passed: result.is_err(),
            expected: "Error (EINVAL)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_err() { None } else { Some("Expected error for oversized length".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        Ok(())
    }
    
    /// Test sys_munmap
    fn test_sys_munmap(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let syscall_name = "sys_munmap".to_string();
        
        // Test 1: Unmap null pointer
        let start = std::time::Instant::now();
        let result = syscalls::sys_munmap(std::ptr::null_mut(), 0);
        let execution_time = start.elapsed().as_micros() as u64;
        
        let test_result = SyscallTestResult {
            syscall_name: syscall_name.clone(),
            test_case: "Unmap null pointer".to_string(),
            passed: result.is_err(),
            expected: "Error (EINVAL)".to_string(),
            actual: format!("{:?}", result),
            error: if result.is_err() { None } else { Some("Expected error for null pointer".to_string()) },
            execution_time: Some(execution_time),
        };
        
        self.results.add_result(test_result);
        
        Ok(())
    }
}

/// Run the complete ABI conformance test suite
pub fn run_abi_conformance_tests(config: Option<ConformanceTestConfig>) -> Result<ConformanceTestResults, Box<dyn std::error::Error>> {
    let config = config.unwrap_or_default();
    let mut test_suite = AbiConformanceTestSuite::new(config);
    
    test_suite.run_all_tests()?;
    
    Ok(test_suite.results)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_conformance_test_results() {
        let mut results = ConformanceTestResults::new();
        
        // Add some test results
        let test_result = SyscallTestResult {
            syscall_name: "test_syscall".to_string(),
            test_case: "Test case".to_string(),
            passed: true,
            expected: "Success".to_string(),
            actual: "Success".to_string(),
            error: None,
            execution_time: Some(100),
        };
        
        results.add_result(test_result);
        results.calculate_pass_rate();
        
        assert_eq!(results.total_tests, 1);
        assert_eq!(results.passed, 1);
        assert_eq!(results.failed, 0);
        assert_eq!(results.pass_rate, 100.0);
    }
    
    #[test]
    fn test_conformance_test_suite_creation() {
        let config = ConformanceTestConfig::default();
        let test_suite = AbiConformanceTestSuite::new(config);
        
        assert_eq!(test_suite.results.total_tests, 0);
        assert_eq!(test_suite.results.passed, 0);
        assert_eq!(test_suite.results.failed, 0);
    }
    
    #[test]
    fn test_config_default() {
        let config = ConformanceTestConfig::default();
        
        assert_eq!(config.destructive, false);
        assert_eq!(config.performance, false);
        assert_eq!(config.max_iterations, 1000);
        assert_eq!(config.timeout_seconds, 30);
    }
}
