load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_binary(
    name = "ngfs_read_verify",
    srcs = ["ngfs_read_verify.py"],
    visibility = ["//visibility:public"],
    deps = [],
)

py_library(
    name = "ngfs_python_lib",
    srcs = ["ngfs_read_verify.py"],
    visibility = ["//visibility:public"],
)
